# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/claude_text_editor',
                'doc_host': 'https://mldurga.github.io',
                'git_url': 'https://github.com/mldurga/claude_text_editor',
                'lib_path': 'claude_text_editor'},
  'syms': {'claude_text_editor.core': {'claude_text_editor.core.foo': ('core.html#foo', 'claude_text_editor/core.py')}}}
